<table  style="background-color: #FFB7C5; width:100%;color:black;">
    <thead>
        <tr>
            <th style="text-align:center;border:solid;border-width:1px;font-size:20pt;width:70%;">TD n°22 : Les algorithmes gloutons</th>
            <th style="text-align:center;border:solid;border-width:1px;font-size:12pt;width:30%;">Thème 7 : Algorithmique</th>
        </tr>
        <tr>
            <th style="text-align:center;border:solid;border-width:1px;font-size:15pt;width:70%;">Complément Cours - Python</th>
            <th style="text-align:center;border:solid;border-width:1px;font-size:12pt;width:30%;"></th>
        </tr>
    </thead>
</table>


# Problème d’optimisation : Le voyageur

## Mise en oeuvre : Python 

**Principe du Programme :** 

+ Les villes sont individuellement sous forme de dictionnaires avec les autres villes en clé et les distances correspondantes en valeurs. Un autre dictionnaire est créé pour regrouper l’ensemble des villes :


In [2]:
''' Nous créons un dictionnaire les_villes qui va contenir des dictionnaires pour stocker les
distances entre villes '''

brest = {'Bordeaux':598, 'Lille':708, 'Lyon':872, 'Marseille':1130, 'Paris':572}
bordeaux = {'Brest':598, 'Lille':802, 'Lyon':520, 'Marseille':637, 'Paris':554}
lille = {'Brest':708, 'Bordeaux':802, 'Lyon':650, 'Marseille':1002, 'Paris':225}
lyon = {'Brest':872, 'Bordeaux':520, 'Lille':650, 'Marseille':367, 'Paris':465}
marseille = {'Brest':1130, 'Bordeaux':637, 'Lille':1002, 'Lyon':367, 'Paris':777}
paris = {'Brest':572, 'Bordeaux':554, 'Lille':225, 'Lyon':465, 'Marseille':777}
les_villes = {'Brest':brest, 'Bordeaux':bordeaux, 'Lille':lille, 'Lyon':lyon, 'Marseille':marseille, 'Paris':paris}

* Une fonction <code>plus_proche_voisin(ville,les_villes_voisines,Non_Visitees)</code> , qui renvoie le nom de la ville non encore visitée la plus proche ainsi que la distance correspondante.

In [3]:
def plus_proche_voisin(ville,les_villes_voisines,Non_Visitees):
    if Non_Visitees==[ville]:
        dist=0
    else:
        dist=1E99
    pp=None
   
    for v,d in les_villes_voisines.items():
        
        if v in Non_Visitees:
            if d<dist:
                dist=d
                pp=v
    return pp,dist

ville='Lille'
print(plus_proche_voisin(ville,les_villes[ville],les_villes.keys()))

('Paris', 225)


* Une fonction principal <code>trajet</code> qui prend en paramètre la ville de départ,le dictionnaire des villes à visiter.

In [4]:
def trajet(depart,avisitees):
    Nvisitees=[vil for vil in avisitees.keys()]
    taille=len(avisitees)
    ville=depart
    parcours=[depart]
    distance=0
    for i in range(taille-1):
        Nvisitees.remove(ville)
        ville,dist=plus_proche_voisin(ville,avisitees[ville],Nvisitees)
        distance+=dist
        parcours.append(ville)
        print(f"ville suivante {ville} avec une distance de {dist} km soit une distance total {distance} km")
    parcours.append(depart)
    distance+=les_villes[ville][depart]
    print(f"ville suivante {ville} avec une distance de {dist} km soit une distance total {distance} km")
    return parcours,distance

print(trajet('Lyon',les_villes))

ville suivante Marseille avec une distance de 367 km soit une distance total 367 km
ville suivante Bordeaux avec une distance de 637 km soit une distance total 1004 km
ville suivante Paris avec une distance de 554 km soit une distance total 1558 km
ville suivante Lille avec une distance de 225 km soit une distance total 1783 km
ville suivante Brest avec une distance de 708 km soit une distance total 2491 km
ville suivante Brest avec une distance de 708 km soit une distance total 3363 km
(['Lyon', 'Marseille', 'Bordeaux', 'Paris', 'Lille', 'Brest', 'Lyon'], 3363)


Tester ce code avec d'autres villes de départ.

### Version force brute

In [5]:
# Cette variable va contenir la plus petite distance trouvée par comparaison.
# Initialement j'y place donc une très grande valeur.
meilleur = 1E999

# Nous créons un dictionnaire les_villes qui va contenir des dictionnaires pour stocker les distances entre villes
brest = {'Bordeaux':598, 'Lille':708, 'Lyon':872, 'Marseille':1130, 'Paris':572}
bordeaux = {'Brest':598, 'Lille':802, 'Lyon':520, 'Marseille':637, 'Paris':572}
lille = {'Brest':708, 'Bordeaux':802, 'Lyon':650, 'Marseille':1002, 'Paris':225}
lyon = {'Brest':872, 'Bordeaux':520, 'Lille':650, 'Marseille':367, 'Paris':465}
marseille = {'Brest':1130, 'Bordeaux':637, 'Lille':1002, 'Lyon':367, 'Paris':777}
paris = {'Brest':572, 'Bordeaux':554, 'Lille':225, 'Lyon':465, 'Marseille':777}

les_villes = {'Brest':brest, 'Bordeaux':bordeaux, 'Lille':lille, 'Lyon':lyon, 'Marseille':marseille, 'Paris':paris}

# Nous créons un premier tableau qui va contenir les noms des villes
villes1 = [ville for ville in les_villes.keys()]
ville1 = villes1[0] # on choisit 'Brest' comme "point de départ" du chemin fermé

# On crée le second tableau contenant toutes les villes, sauf Brest.
villes2 = villes1.copy() # On copie le tableau précédent
villes2.remove(ville1) # on enlève le premier choix ('Brest')

for ville2 in villes2 :

    villes3 = villes2.copy() # On copie le tableau précédent
    villes3.remove(ville2) # On enlève le choix qui vient d'être fait

    for ville3 in villes3 :

        villes4 = villes3.copy() # On copie le tableau précédent
        villes4.remove(ville3) # on enlève le choix de ville qui vient d'être fait

        for ville4 in villes4 :

            villes5 = villes4.copy()
            villes5.remove(ville4)

            for ville5 in villes5 :

                villes6 = villes5.copy()
                villes6.remove(ville5)
                ville6 = villes6[0]

                distance = les_villes[ville1][ville2] # distance entre ville 1 et 2
                distance = distance + les_villes[ville2][ville3] # + distance entre ville 2 et 3
                distance = distance + les_villes[ville3][ville4]
                distance = distance + les_villes[ville4][ville5]
                distance = distance + les_villes[ville5][ville6]
                distance = distance + les_villes[ville6][ville1] # + distance pour repartir au départ
                if distance < meilleur : # Si ce choix de villes est meilleur en terme de distance
                    meilleur = distance # On remplace meilleur par cette valeur
                    itineraire = f"{ville1}-{ville2}-{ville3}-{ville4}-{ville5}-{ville6}" # On crée un string contenant l'itinéraire qu'on vient de séléctionner pour le moment

# On affiche le résultat
print(f"{itineraire} en {meilleur} km")

Brest-Bordeaux-Marseille-Lyon-Paris-Lille en 3000 km


### <img src="https://drive.google.com/uc?id=1fYHzp1GqR6Tepu-6SIFhAci5g1CK8R7e" height="30px" align="left" hspace="1px" alt="New"></img>  Qualité de l’approximation  
* La solution donnée par l’algorithme glouton n’est pas nécessairement optimale. Peut-on néanmoins s’attendre à un certain niveau de qualité ?
* Si oui, ce niveau de qualité attendu est-il garanti, c’est-à-dire respecte même dans le pire des scénarios ?
* Ou bien est-il seulement hautement probable, c’est-à-dire généralement respecté mais avec des exceptions ?

Les réponses à ces questions dépendent fortement du problème considéré.  
Pour notre problème du voyageur, ii a été démontré que lorsque le nombre de villes devient grand, le rapport entre la. solution gloutonne et la solution optimale est dans le pire des cas proportionnel **au logarithme du nombre de villes**.


[Voir une simulation](http://lycee.stanislas.info.free.fr/Algorithme/Glouton/Glouton.html)


# Problème : Rendu de monnaie

Nous allons étudier un problème d'optimisation classique : le problème du rendu de monnaie de manière optimale. On cherche à rendre la monnaie avec un nombre minimal de pièces et billets.

## Implémentation de l'algorithme glouton  

Programmer cet algorithme en langage python. Programmer une fonction rendu_monnaie_glouton(systeme,somme) qui possède comme paramètres  
    - un système de pièces et de billets sous forme de liste de nombres ;
    - une somme à rendre   
    Cette fonction renvoie une liste de nombres qui caractérise la monnaie à rendre. Vous pouvez prendre comme jeu de test l'exemple de présentation.  
    Il faudra penser à gérer le fait que l'algorithme ne trouve pas de solution dans certains cas.

    Quelques aides :  

    * penser à trier par ordre décroissant la liste des pièces et billets.  
    * penser à gérer l'absence de solution globale.

In [6]:
euros = [100, 50, 20, 10, 5, 2, 1, 0.50, 0.20, 0.10, 0.05, 0.02,0.01]

def rendu_monnaie_glouton(s, pieces):
    """Renvoie la solution gloutonne du rendu de monnaie d'une somme s entière et positive.
    Le tableau pieces contient les valeurs des pièces à disposition dans l'ordre décroissant."""
    solution = []
    i = 0 # position de la première pièce à tester (la plus grande)
    while s >= 0 and i < len(pieces): # tant qu'il reste de l'argent à rendre et que toutes les pièces n'ont pas été testées
        valeur = pieces[i] # on prend la pièce d'indice i
        if valeur <= s: # s'il est possible de rendre la pièce
            solution.append(valeur) # on l'ajoute à solution
            s = s - valeur # et on déduit sa valeur de la somme à rendre
        else:
            i = i + 1 # sinon on passe à la pièce immédiatement inférieure
    if s>0 and s <=0.01:
        solution.append(pieces[len(pieces)-1])
    return solution
print(rendu_monnaie_glouton(147.35, euros))

[100, 20, 20, 5, 2, 0.2, 0.1, 0.02, 0.02, 0.01]


# Exercice : Plus beaucoup de place sur ta clé USB ?  

>**Objectifs** : 
- implémenter un algorithme glouton pour trouver une solution à un problème
- implémenter l'algorithme de *force brute* pour déterminer la solution optimale et la comparer à la solution gloutonne

### Introduction

Nous disposons d’une clé USB qui est déjà bien remplie et sur laquelle il ne reste que 5 Go de libre. Nous souhaitons copier sur cette  clé  des  fichiers  vidéos  pour  l’emporter  en  voyage.  Chaque  fichier  a  un poids  et  chaque  vidéo  a  une  durée.  La  durée  n’est pas proportionnelle à la taille car les fichiers sont de format différents, certaines vidéos sont de grande qualité, d’autres sont très compressées. Le tableau qui suit présente les 7 fichiers disponibles avec les durées données en minutes.

| Nom 	| Durée en min (valeur) 	| Poids |
|---------	|-------	|---------	|
| Vidéo A 	| 114   	| 4.57 Go 	|
| Vidéo B 	| 32    	| 630 Mo  	|
| Vidéo C 	| 20    	| 1.65 Go 	|
| Vidéo D 	| 4     	| 85 Mo   	|
| Vidéo E 	| 18    	| 2,15 Go 	|
| Vidéo F 	| 80    	| 2,71 Go 	|
| Vidéo G 	| 5     	| 320 Mo  	|  


>**Problème** : Quelles vidéos copier sur la clé USB pour que la durée des vidéos soient la plus grande possible tout en ne dépassant pas 5 Go ?

Vous allez implémenter (= programmer) une solution gloutonne pour résoudre ce problème, puis vous implémenterez l'algorithme de *force brute* qui donnera la solution optimale au problème. La **stratégie gloutonne retenue sera de toujours prendre la vidéo de plus grande durée** n'excédant pas la capacité restante de poids.

### Représentation des données

Dans la suite, on utilisera des dictionnaires de la forme suivante pour représenter chaque vidéo, la durée étant donnée minute et le poids étant donné en Go.

```python
{'nom': 'Vidéo A', 'duree': 114, 'poids': 4.57}
```

On peut alors mémoriser les 7 vidéos dans le tableau `table_videos` suivant.


```python
table_videos = [{'nom' : 'video A', 'duree' : 114, 'poids' : 4.57},
                {'nom' : 'video B', 'duree' : 32, 'poids' : 0.63},
                {'nom' : 'video C', 'duree' : 20, 'poids' : 1.65},
                {'nom' : 'video D', 'duree' : 4, 'poids' : 0.085},
                {'nom' : 'video E', 'duree' : 18, 'poids' : 2.15},
                {'nom' : 'video F', 'duree' : 80, 'poids' : 2.71},
                {'nom' : 'video G', 'duree' : 5, 'poids' : 0.32}]
```

On peut alors accéder aux éléments de cette table.


```python
table_videos[0]['nom']
```


```python
table_videos[3]['duree']
```


```python
table_videos[6]['poids']
```



In [15]:
table_videos = [{'nom' : 'video A', 'duree' : 114, 'poids' : 4.57},
                {'nom' : 'video B', 'duree' : 32, 'poids' : 0.63},
                {'nom' : 'video C', 'duree' : 20, 'poids' : 1.65},
                {'nom' : 'video D', 'duree' : 4, 'poids' : 0.085},
                {'nom' : 'video E', 'duree' : 18, 'poids' : 2.15},
                {'nom' : 'video F', 'duree' : 80, 'poids' : 2.71},
                {'nom' : 'video G', 'duree' : 5, 'poids' : 0.32}]

### Ecriture des fonctions utiles

#### Accès au poids d'une vidéo

Pour résoudre le problème, on a besoin d'accéder au poids des vidéos pour vérifier la contrainte du poids maximal. La fonction suivante permet de renvoyer le poids d'une vidéo entrée en paramètre (sous la forme d'un dictionnaire comme vu précédemment). Quelques assertions devant être vérifiées par la fonction ont été écrites.


In [16]:
def poids(video):
    return video['poids']
    

In [17]:
assert poids({'nom' : 'video A', 'duree' : 114, 'poids' : 4.57}) == 4.57
assert poids({'nom' : 'video D', 'duree' : 4, 'poids' : 0.085}) == 0.085
assert poids({'nom' : 'video G', 'duree' : 5, 'poids' : 0.32}) == 0.32

#### Accès à la durée d'une vidéo

De même, comme la stratégie gloutonne choisie prévoit de prendre la vidéo de plus grande durée (valeur) n'excédant pas la capacité restante de poids, il est nécessaire de pouvoir accéder aux durées de chacune des vidéos retenues.

**Question 2 :**  
Ecrivez une fonction `duree(video)` qui renvoie la durée (= valeur) d'une video entrée en paramètre (sous la forme d'un dictionnaire vu précédemment). Quelques assertions devant être vérifiées par votre fonction sont données ci-dessous.



In [18]:
def duree(video):
    return video['duree']

In [19]:
assert duree({'nom' : 'video A', 'duree' : 114, 'poids' : 4.57}) == 114
assert duree({'nom' : 'video D', 'duree' : 4, 'poids' : 0.085}) == 4
assert duree({'nom' : 'video G', 'duree' : 5, 'poids' : 0.32}) == 5

#### Calculer le poids total et la durée totale d'une table de vidéos

Enfin, il sera nécessaire de pouvoir calculer le poids et la durée totale d'une table de vidéos pour savoir si la contrainte de capacité maximale est respectée d'une part, et pour connaître la durée totale qui est la valeur à maximiser.

**Question 3 :**  
Ecrivez une fonction `poids_total(table_videos)` qui renvoie le poids total `poids_t` des vidéos présentes dans `table_videos`. Quelques assertions devant être vérifiées par votre fonction sont données ci-dessous.


In [20]:
def poids_total(table_videos):
    poids_t = 0
    for v in table_videos:
        poids_t+=poids(v)
    
    return poids_t

In [21]:
table1 = [{'nom' : 'video C', 'duree' : 20, 'poids' : 1.65}]
table2 = [{'nom' : 'video A', 'duree' : 114, 'poids' : 4.57},
           {'nom' : 'video B', 'duree' : 32, 'poids' : 0.63}]
table3 = [{'nom' : 'video A', 'duree' : 114, 'poids' : 4.57},
          {'nom' : 'video B', 'duree' : 32, 'poids' : 0.63},
          {'nom' : 'video C', 'duree' : 20, 'poids' : 1.65}]

assert poids_total(table1) == 1.65   # on compare des nombres réels mais on a pris soin de bien choisir les exemples
assert poids_total(table2) == 5.2
assert poids_total(table3) == 6.85
assert poids_total([]) == 0   # table vide testée

**Question 4 :**  
Ecrivez une fonction `duree_totale(table_videos)` qui renvoie la durée totale `duree_t` des vidéos présentes dans `table_videos`. Quelques assertions devant être vérifiées par votre fonction sont données ci-dessous.

In [22]:
def duree_totale(table_videos):
    duree_t = 0
    for v in table_videos:
        duree_t+=duree(v)

    
    return duree_t

In [23]:
table1 = [{'nom' : 'video C', 'duree' : 20, 'poids' : 1.65}]
table2 = [{'nom' : 'video A', 'duree' : 114, 'poids' : 4.57},
           {'nom' : 'video B', 'duree' : 32, 'poids' : 0.63}]
table3 = [{'nom' : 'video A', 'duree' : 114, 'poids' : 4.57},
          {'nom' : 'video B', 'duree' : 32, 'poids' : 0.63},
          {'nom' : 'video C', 'duree' : 20, 'poids' : 1.65}]

assert duree_totale(table1) == 20
assert duree_totale(table2) == 146
assert duree_totale(table3) == 166
assert duree_totale([]) == 0   # table vide testée
assert duree_totale(table_videos) == 273 # table avec toutes les vidéos

### Implémentation de l'algorithme glouton

#### Tri préalable

Comme la stratégie gloutonne retenue prévoit de choisir les vidéos de plus grande durée n'excédant pas la capacité restante, il est judicieux de commencer par trier les vidéos de `table_videos` par durée décroissante.

**Question 5 :** 
Utilisez la fonction `sorted` de Python pour obtenir un *nouveau* tableau (appelé `table_triee`) contenant les vidéos de `table_videos` triées par durée décroissante. *Indication* : l'instruction `help(sorted)` permet d'afficher l'aide de la fonction `sorted` (vous pouvez aussi revoir le cours sur les tris de table si nécessaire).


In [25]:
# à compléter
table_triee = sorted(table_videos,key=duree)
table_triee # pour afficher le résultat

[{'nom': 'video D', 'duree': 4, 'poids': 0.085},
 {'nom': 'video G', 'duree': 5, 'poids': 0.32},
 {'nom': 'video E', 'duree': 18, 'poids': 2.15},
 {'nom': 'video C', 'duree': 20, 'poids': 1.65},
 {'nom': 'video B', 'duree': 32, 'poids': 0.63},
 {'nom': 'video F', 'duree': 80, 'poids': 2.71},
 {'nom': 'video A', 'duree': 114, 'poids': 4.57}]

In [28]:
def tri_rapport_decroissant(table_videos):
    table_triee = sorted(table_videos, key = rapport_valeur_poids, reverse = True)
    return table_triee

def tri_valeur_decroissante(tables_videos):
    table_triee = sorted(table_videos, key = duree, reverse = True)
    return table_triee

def tri_poids_croissant(tables_videos):
    table_triee = sorted(table_videos, key = poids)
    return table_triee

#### Algorithme glouton

**Question 6 :**  
en vous inspirant de l'implémentation de l'algorithme glouton du rendu de monnaie (voir cours), écrivez une fonction `glouton(table_videos, poids_max)` qui prend en paramètre une table de vidéos `table_videos` et un poids maximal `poids_max` et renvoie une liste `solution_gloutonne` contenant les vidéos de la solution gloutonne au problème. La solution gloutonne à trouver est donnée dans l'assertion qui suit.



In [26]:
def glouton(table_videos, poids_max):
    table_triee = tri_poids_croissant(table_videos)
    poids_total = 0
    solution_gloutonne = []
    # à compléter
    i = 0
    while poids_total < poids_max and i < len(table_triee):  # tant que le poids max n'est pas atteint et que l'on n'a pas traité toutes les vidéos
        video = table_triee[i]
        poids_video = poids(video)
        if poids_total + poids_video <= poids_max:  # on ajoute la vidéo d'indice i à notre solution
            solution_gloutonne.append(video)
            poids_total = poids_total + poids_video  # on met à jour le poids total de note solution
        i = i + 1
    return solution_gloutonne

In [27]:
assert glouton(table_videos, 5) == [{'nom': 'video A', 'duree': 114, 'poids': 4.57},
                                    {'nom': 'video G', 'duree': 5, 'poids': 0.32},
                                    {'nom': 'video D', 'duree': 4, 'poids': 0.085}]

NameError: name 'tri_poids_croissant' is not defined

**Question 7 :**  
Utilisez la fonction `duree_totale` pour déterminer la durée totale de la solution gloutonne. Quelle est sa durée totale ?



### Implémentation de la *force brute*

Le principe est simple : il faut étudier tous les cas possibles. Ainsi, pour appliquer cette stratégie, il faut :
1. d'abord *énumérer* toutes les combinaisons possibles de vidéos 
2. puis conserver celles dont la capacité maximale n'est pas dépassée
3. enfin, trouver la meilleure solution parmi les combinaisons restantes

>**Remarque** : Dans un souci de simplicité, il a été fait le choix de ne pas utiliser de fonctions pour implémenter la stratégie de force brute. Vous pourrez trouver un code plus propre (mais plus complexe) en suivant ce [lien](#).



In [8]:
table_videos = [{'nom' : 'video A', 'duree' : 114, 'poids' : 4.57},
                {'nom' : 'video B', 'duree' : 32, 'poids' : 0.63},
                {'nom' : 'video C', 'duree' : 20, 'poids' : 1.65},
                {'nom' : 'video D', 'duree' : 4, 'poids' : 0.085},
                {'nom' : 'video E', 'duree' : 18, 'poids' : 2.15},
                {'nom' : 'video F', 'duree' : 80, 'poids' : 2.71},
                {'nom' : 'video G', 'duree' : 5, 'poids' : 0.32}]

#### Etape 1 : énumération de toutes les combinaisons

Il s'agit de la difficulté majeure. Dans une combinaison de vidéos, chaque vidéo de départ est prise ou non, il s'agit d'une donnée binaire. Ainsi, une approche consiste à créer des mots binaires représentant chaque combinaison. Par exemple, le mot '1101001' signifie qu'on prend les vidéos A, B, D et G tandis que le mot '1111111' signifie que l'on prend toutes les vidéos.

Dans notre exemple, nous avons 7 vidéos donc il y a $2^{7} = 128$ combinaisons possibles. De manière générale il y a donc $2^n$ combinaisons pour un ensemble de $n$ vidéos.

On va construire un tableau `combinaisons` contenant toutes les combinaisons binaires. Pour cela, l'idée est de commencer par construire un tableau `tab_entiers` contenant tous les entiers compris entre $0$ et $2^n-1$.



In [9]:
n = len(table_videos)  # nombre de vidéos
tab_entiers = [i for i in range(2**n)]  # création d'un tableau avec tous les entiers entre 0 et 2**n-1
print(tab_entiers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127]


Ensuite, on construit un autre tableau `tab_binaire` avec les conversions binaires de chaque entier. 

>**Astuce** : la fonction `bin` prend un entier en paramètre et renvoie sa valeur binaire sous forme d'une chaîne de caractères. Par exemple, `bin(12)` renvoie la chaîne `'0b1101'`. Il suffira de supprimer les caractères `'0b'` en tête pour obtenir l'écriture binaire. On veillera également à compléter avec des zéros devant pour obtenir un mot de la longueur désirée.


In [10]:
tab_binaire = [bin(i)[2:] for i in tab_entiers]  # conversion binaire des entiers du tableau précédent, le [2:] permet de supprimer les caractères de tête '0b' renvoyés par la fonction bin
print(tab_binaire)

['0', '1', '10', '11', '100', '101', '110', '111', '1000', '1001', '1010', '1011', '1100', '1101', '1110', '1111', '10000', '10001', '10010', '10011', '10100', '10101', '10110', '10111', '11000', '11001', '11010', '11011', '11100', '11101', '11110', '11111', '100000', '100001', '100010', '100011', '100100', '100101', '100110', '100111', '101000', '101001', '101010', '101011', '101100', '101101', '101110', '101111', '110000', '110001', '110010', '110011', '110100', '110101', '110110', '110111', '111000', '111001', '111010', '111011', '111100', '111101', '111110', '111111', '1000000', '1000001', '1000010', '1000011', '1000100', '1000101', '1000110', '1000111', '1001000', '1001001', '1001010', '1001011', '1001100', '1001101', '1001110', '1001111', '1010000', '1010001', '1010010', '1010011', '1010100', '1010101', '1010110', '1010111', '1011000', '1011001', '1011010', '1011011', '1011100', '1011101', '1011110', '1011111', '1100000', '1100001', '1100010', '1100011', '1100100', '1100101', '11

Enfin, pour obtenir le tableau `combinaisons`, on prendra le soin de compléter avec autant de zéros que nécessaires les valeurs binaires précédentes pour obtenir des mots de longueur 7, représentant les combinaisons possibles de vidéos.

In [11]:
combinaisons = ['0'*(n-len(k)) + k for k in tab_binaire]  # ajout des zéros pour obtenir des mots binaires de longueur n

On peut vérifier que le tableau `combinaisons` contient bien tous les 128 mots binaires de longueur 7.

In [12]:
combinaisons

['0000000', '0000001', '0000010', '0000011', '0000100', '0000101', '0000110', '0000111', '0001000', '0001001', '0001010', '0001011', '0001100', '0001101', '0001110', '0001111', '0010000', '0010001', '0010010', '0010011', '0010100', '0010101', '0010110', '0010111', '0011000', '0011001', '0011010', '0011011', '0011100', '0011101', '0011110', '0011111', '0100000', '0100001', '0100010', '0100011', '0100100', '0100101', '0100110', '0100111', '0101000', '0101001', '0101010', '0101011', '0101100', '0101101', '0101110', '0101111', '0110000', '0110001', '0110010', '0110011', '0110100', '0110101', '0110110', '0110111', '0111000', '0111001', '0111010', '0111011', '0111100', '0111101', '0111110', '0111111', '1000000', '1000001', '1000010', '1000011', '1000100', '1000101', '1000110', '1000111', '1001000', '1001001', '1001010', '1001011', '1001100', '1001101', '1001110', '1001111', '1010000', '1010001', '1010010', '1010011', '1010100', '1010101', '1010110', '1010111', '1011000', '1011001', '1011010'

#### Etape 2 : conservation des combinaisons valides

On cherche maintenant à conserver uniquement les combinaisons valides, c'est-à-dire celles ne dépassant pas la capacité maximale de 5 Go. Par exemple : 
- `'0000001'` est à conserver puisqu'il s'agit uniquement de la vidéo G de 0.32 Go
- `'1010000'` n'est pas à conserver car le poids total de cette combinaison (vidéos A et C) vaut 4.57 + 1.65 = 6.22 Go, ce qui dépasse la capacité maximale autorisée.

Pour cela, on peut calculer le poids total de chaque combinaison. Si celui-ci est inférieur au poids maximal autorisé, alors la combinaison est valide et on la conserve. 
 
**Question 8 :**  
Complétez le programme suivant pour qu'en fin d'exécution la liste `combinaisons_valides` contienne tous les couples `(combi, duree_combi)` des combinaisons valides et de leur durée. L'assertion qui suit indique le nombre de combinaisons valides.



In [ ]:
n = len(table_videos)
poids_max = 5
combinaisons_valides = []
for combi in combinaisons: # on parcourt chaque combinaison du tableau combinaisons
    poids_combi = 0
    duree_combi = 0
    for i in range(n):  # on parcourt la combinaison caractère par caractère
        # à compléter
        # si le caractère est '1', alors on met à jour la durée et le poids de la combinaison avec ceux de la vidéo
    # si la combi est valide alors on ajoute le couple (combi, duree_combi)à notre liste de combinaisons valides 
    

In [ ]:
assert len(combinaisons_valides) == 51 

Si vous ne parvenez pas à trouver la liste souhaitée, la voici. Vous pourrez continuer en l'utilisant.

In [13]:
combinaisons_valides = [('0000000', 0), 
                        ('0000001', 5), 
                        ('0000010', 80), 
                        ('0000011', 85),
                        ('0000100', 18), 
                        ('0000101', 23),
                        ('0000110', 98),
                        ('0001000', 4),
                        ('0001001', 9),
                        ('0001010', 84),
                        ('0001011', 89),
                        ('0001100', 22),
                        ('0001101', 27),
                        ('0001110', 102),
                        ('0010000', 20),
                        ('0010001', 25),
                        ('0010010', 100),
                        ('0010011', 105),
                        ('0010100', 38),
                        ('0010101', 43),
                        ('0011000', 24),
                        ('0011001', 29),
                        ('0011010', 104),
                        ('0011011', 109),
                        ('0011100', 42),
                        ('0011101', 47),
                        ('0100000', 32),
                        ('0100001', 37),
                        ('0100010', 112),
                        ('0100011', 117),
                        ('0100100', 50),
                        ('0100101', 55),
                        ('0101000', 36),
                        ('0101001', 41),
                        ('0101010', 116),
                        ('0101011', 121),
                        ('0101100', 54),
                        ('0101101', 59),
                        ('0110000', 52),
                        ('0110001', 57),
                        ('0110010', 132),
                        ('0110100', 70),
                        ('0110101', 75),
                        ('0111000', 56),
                        ('0111001', 61),
                        ('0111100', 74),
                        ('0111101', 79),
                        ('1000000', 114),
                        ('1000001', 119),
                        ('1001000', 118),
                        ('1001001', 123)]

#### Etape 3 : trouver la meilleure solution

C'est très simple puisqu'il suffit de déterminer la combinaison valide de durée maximale. Cela revient donc à une recherche de maximum.

**Question 9 :**  
Ecrivez un programme permettant de trouver la solution optimale et sa durée totale.




Vous devez trouver que la solution optimale est la combinaison `'0110010'` d'une durée de 132 min.

**Question 10 :**  
Comparez la solution optimale et la solution gloutonne trouvée précédemment.

**Question 11 :**  
Ecrivez un programme permettant d'afficher une liste `liste_optimale` contenant les noms des vidéos correspondant à la solution optimale.

In [ ]:
liste_optimale = []
# à compléter

        
print("la meilleure solution est de choisir :", liste_optimale)