name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install --upgrade pip
      - run: pip install mkdocs-material
      - run: pip install mkdocs-jupyter
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-git-revision-date-plugin
      - run: pip install mkdocs-page-pdf
      - run: pip install pyppeteer
      - run: pip install mkdocs-graphviz
      - run: mkdocs gh-deploy --force

 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
